"""add rationale to training_plans

Revision ID: 35f5ff21bfdb
Revises: 0fe58783e2d1
Create Date: 2026-04-30 14:30:00.977787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f5ff21bfdb'
down_revision: Union[str, None] = '0fe58783e2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_plans', 'rationale')
    # ### end Alembic commands ###
